version: '3.9'
services:
  db:
    image: mysql:8.1.0
    volumes:
      - data:/var/lib/mysql    
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
    ports:
      - "3306:3306"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 20s
        retries: 10     
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    environment:
      RAILS_ENV: production   
      RUBYOPT: -W0 
    ports:
      - "8080:3000"
    depends_on:
         db:
            condition: service_healthy        
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development  
      #RAILS_SERVE_STATIC_FILES: 'true'
      #RAILS_LOG_TO_STDOUT: 'true'      
      RUBYOPT: -W0 
    ports:
      - "3000:3000"
    depends_on:
         db:
            condition: service_healthy      
    tty: true

volumes:
  data:
  bundle:

networks: 
  default:
    driver: bridge
    name: osb