version: '3'
services:
  db:
    image: mysql
    volumes:
      - data:/var/lib/mysql    
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: Passw0rd
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    volumes:
      - ./docker/web/etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      RAILS_ENV: production   
      RUBYOPT: -W0 
    ports:
      - "80:3000"
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - .:/code
      - bundle:/usr/local/bundle
    environment:
      RAILS_ENV: development   
      RUBYOPT: -W0 
    ports:
      - "3000:3000"
    depends_on:
      - db
    tty: true

volumes:
  data:
  bundle:

networks: 
  default:
    driver: bridge
    name: osb